In [1]:
import pandas as pd
print("Jupyter is working!")

Jupyter is working!

In [2]:
import pandas as pd

df = pd.read_excel("ApexPlanet DataAnalytics Dataset.xlsx")

df.head()

FileNotFoundError: [Errno 2] No such file or directory: 'ApexPlanet DataAnalytics Dataset.xlsx'

In [3]:
import os

print(os.getcwd())
print(os.listdir())

C:\Users\B RISHITHA
[' task1_data_analysis.ipynb', '.anaconda', '.appletviewer', '.conda', '.continuum', '.docker', '.idlerc', '.ipynb_checkpoints', '.ipython', '.m2', '.vscode', '.vscode-shared', 'anaconda3_old', 'AppData', 'Application Data', 'Contacts', 'Cookies', 'Documents', 'Downloads', 'Favorites', 'Links', 'Local Settings', 'Music', 'My Documents', 'NetHood', 'NTUSER.DAT', 'ntuser.dat.LOG1', 'ntuser.dat.LOG2', 'NTUSER.DAT{8927b1a7-b49f-11ef-adb3-282e897391b3}.TM.blf', 'NTUSER.DAT{8927b1a7-b49f-11ef-adb3-282e897391b3}.TMContainer00000000000000000001.regtrans-ms', 'NTUSER.DAT{8927b1a7-b49f-11ef-adb3-282e897391b3}.TMContainer00000000000000000002.regtrans-ms', 'ntuser.ini', 'OneDrive', 'PrintHood', 'Recent', 'Saved Games', 'Searches', 'SendTo', 'source', 'Start Menu', 'Templates', 'Videos']

In [4]:
import os

print(os.listdir("Downloads"))

['3fc2e3cb-c4b3-4156-93db-f80be71141f0.pdf', '5d4f6cec-1589-4b7a-a192-a9371e5068cc.pdf', '60-days.pdf', '7043d04a-7223-48fc-95f1-5ca402983ac1.pdf', '797a3d55-69fc-4c3f-8f0a-7958ef579bb0.pdf', '7b8cc86b-7635-475f-9e70-0e33bb6f0297.pdf', '81bb4862-7d9e-4f98-b98c-55be3d836ae7.pdf', 'a2706f78-7f13-41a7-aefc-9dbf456b00cd.pdf', 'Agent iq certificate.pdf', 'Anaconda3-2025.12-2-Windows-x86_64.exe', 'Apache-NetBeans-27.exe', 'ApexPlanet_DataAnalytics_Dataset.xlsx', 'AWSAcademy12NEW20260316-33-3dwdvf.pdf', 'AWS_Academy_Graduate___Machine_Learning_for_Natural_Language_Processing___Training_Badge_Badge20260316-33-j5cujc.pdf', 'AWS_Academy_Graduate___Machine_Learning_Foundations___Training_Badge_Badge20260316-33-s4hbap.pdf', 'ChromeSetup.exe', 'coverletter.rishitha (1).docx', 'coverletter.rishitha (2).docx', 'coverletter.rishitha (3).docx', 'coverletter.rishitha.docx', 'd777e796-df46-4b6b-8082-5da303e0b641.pdf', 'daa_unit-I.ppt', 'daa_unit-II.ppt', 'daa_unit-III.ppt', 'daa_unit-IV.ppt', 'daa_unit-V-1-Chapter.ppt', 'daa_unit-V-2-Chapter.ppt', 'daa_Unit-VI-1.ppt', 'de73d48c-5af2-46a3-b408-72adea3f95cf.pdf', 'debug.log', 'desktop.ini', 'Docker Desktop Installer.exe', 'DS Unit 1.pptx', 'facd50d1-f37d-482c-b87c-42411f137359.pdf', 'Foundation Week Brief - Medapati Cloud.pdf', 'Gen AI Virtual Internship.pdf', 'Git-2.54.0-64-bit.exe', 'go1.26.4.windows-amd64.msi', 'ideaIC-2025.2.exe', 'jdk-24_windows-x64_bin.exe', 'journeycrafters.pdf', 'KITECH certificate.pdf', 'mysql-installer-community-8.0.46.0.msi', 'OpenJDK8U-jdk_x64_windows_hotspot_8u472b08.zip', 'python-3.13.7-amd64.exe', 'QALR UNIT - 6 PPTS 2024-25 15.06.2025 (1).pptx', 'QALR Unit5 PPTS 2024-25 updated.pptx', 'ts (2).pptx', 'UI UX certificate.pdf', 'Unit  2 QALR.pptx', 'Unit 3 QALR.pptx', 'Unit1 QALR 5-3-25.pdf', 'Unit4   QALR PART 2.pptx', 'Unit4 QALR PATRT 1.pptx', 'VSCodeUserSetup-x64-1.124.0.exe', 'WhatsApp Image 2026-06-01 at 20.00.34.jpeg', 'ZoomInstallerFull.exe', 'Zoom_cm_ds_mfC5TzQf1bI0Zw5b7l8luxAg+G1xHc4IAeS1N@xoUvMF7ieY56OZZ6_k9b99e32fa32afb7e_.exe']

In [5]:
import pandas as pd

df = pd.read_excel(r"C:\Users\B RISHITHA\Downloads\ApesPlanet DataAnalytics Dataset.xlsx")

df.head()

FileNotFoundError: [Errno 2] No such file or directory: 'C:\\Users\\B RISHITHA\\Downloads\\ApesPlanet DataAnalytics Dataset.xlsx'

In [6]:
import os

for file in os.listdir(r"C:\Users\B RISHITHA\Downloads"):
    if file.endswith(".xlsx"):
        print(file)

ApexPlanet_DataAnalytics_Dataset.xlsx

In [7]:
import pandas as pd

df = pd.read_excel(
    r"C:\Users\B RISHITHA\Downloads\ApexPlanet_DataAnalytics_Dataset.xlsx"
)

df.head()

,Order_ID,Order_Date,Customer_ID,Customer_Name,Age,Gender,City,Product,Category,Quantity,Unit_Price,Total_Sales
0,ORD100002,2025-02-25,CUST5529,Customer_227,30.0,Female,Bengaluru,Rice,Grocery,7,2829.77,19808.39
1,ORD100003,2025-10-14,CUST3127,Customer_182,63.0,Male,Bengaluru,Book,Education,5,27906.16,139530.80
2,ORD100004,2025-05-13,CUST8887,Customer_487,62.0,Female,Bengaluru,Book,Education,8,37491.06,299928.48
3,ORD100005,2025-12-02,CUST2515,Customer_470,65.0,Female,Kolkata,Mobile,Electronics,9,28541.36,256872.24
4,ORD100006,2025-11-20,CUST4796,Customer_380,44.0,Male,Bengaluru,Rice,Grocery,10,14036.59,140365.90

In [8]:
print(df.columns)

Index(['Order_ID', 'Order_Date', 'Customer_ID', 'Customer_Name', 'Age',
       'Gender', 'City', 'Product', 'Category', 'Quantity', 'Unit_Price',
       'Total_Sales'],
      dtype='object')

In [9]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 12 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Order_ID       1000 non-null   object
 1   Order_Date     1000 non-null   object
 2   Customer_ID    1000 non-null   object
 3   Customer_Name  1000 non-null   object
 4   Age            980 non-null    float64
 5   Gender         1000 non-null   object
 6   City           987 non-null    object
 7   Product        1000 non-null   object
 8   Category       1000 non-null   object
 9   Quantity       1000 non-null   int64
 10  Unit_Price     1000 non-null   float64
 11  Total_Sales    1000 non-null   float64
dtypes: float64(3), int64(1), object(8)
memory usage: 93.9+ KB

In [10]:
df.isnull().sum()

Order_ID          0
Order_Date        0
Customer_ID       0
Customer_Name     0
Age              20
Gender            0
City             13
Product           0
Category          0
Quantity          0
Unit_Price        0
Total_Sales       0
dtype: int64

In [11]:
print("Duplicate Rows:", df.duplicated().sum())

Duplicate Rows: 0

In [12]:
df.describe()

              Age     Quantity    Unit_Price    Total_Sales
count  980.000000  1000.000000   1000.000000    1000.000000
mean    41.360204     5.435000  25486.783410  139399.439650
std     13.822597     2.838632  14179.402361  114100.051546
min     18.000000     1.000000    145.780000     437.340000
25%     30.000000     3.000000  13895.722500   47066.632500
50%     41.000000     5.000000  25398.740000  108594.025000
75%     54.000000     8.000000  37512.382500  203722.882500
max     65.000000    10.000000  49997.530000  493677.500000

In [13]:
df = df.drop_duplicates()

In [14]:
df.fillna(method='ffill', inplace=True)

C:\Users\B RISHITHA\AppData\Local\Temp\ipykernel_17064\3970806690.py:1: FutureWarning: DataFrame.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  df.fillna(method='ffill', inplace=True)

In [15]:
df.isnull().sum()

Order_ID         0
Order_Date       0
Customer_ID      0
Customer_Name    0
Age              0
Gender           0
City             0
Product          0
Category         0
Quantity         0
Unit_Price       0
Total_Sales      0
dtype: int64

In [16]:
print("Duplicate Rows:", df.duplicated().sum())

Duplicate Rows: 0

In [17]:
df.to_excel("cleaned_dataset.xlsx", index=False)

In [18]:
df.isnull().sum()

Order_ID         0
Order_Date       0
Customer_ID      0
Customer_Name    0
Age              0
Gender           0
City             0
Product          0
Category         0
Quantity         0
Unit_Price       0
Total_Sales      0
dtype: int64

In [19]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 12 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Order_ID       1000 non-null   object
 1   Order_Date     1000 non-null   object
 2   Customer_ID    1000 non-null   object
 3   Customer_Name  1000 non-null   object
 4   Age            1000 non-null   float64
 5   Gender         1000 non-null   object
 6   City           1000 non-null   object
 7   Product        1000 non-null   object
 8   Category       1000 non-null   object
 9   Quantity       1000 non-null   int64
 10  Unit_Price     1000 non-null   float64
 11  Total_Sales    1000 non-null   float64
dtypes: float64(3), int64(1), object(8)
memory usage: 93.9+ KB

In [20]:
print(df.columns)

Index(['Order_ID', 'Order_Date', 'Customer_ID', 'Customer_Name', 'Age',
       'Gender', 'City', 'Product', 'Category', 'Quantity', 'Unit_Price',
       'Total_Sales'],
      dtype='object')

In [21]:
import os

print("Current Folder:", os.getcwd())
print(os.listdir())

Current Folder: C:\Users\B RISHITHA
[' task1_data_analysis.ipynb', '.anaconda', '.appletviewer', '.conda', '.continuum', '.docker', '.idlerc', '.ipynb_checkpoints', '.ipython', '.m2', '.vscode', '.vscode-shared', 'anaconda3_old', 'AppData', 'Application Data', 'cleaned_dataset.xlsx', 'Contacts', 'Cookies', 'Documents', 'Downloads', 'Favorites', 'Links', 'Local Settings', 'Music', 'My Documents', 'NetHood', 'NTUSER.DAT', 'ntuser.dat.LOG1', 'ntuser.dat.LOG2', 'NTUSER.DAT{8927b1a7-b49f-11ef-adb3-282e897391b3}.TM.blf', 'NTUSER.DAT{8927b1a7-b49f-11ef-adb3-282e897391b3}.TMContainer00000000000000000001.regtrans-ms', 'NTUSER.DAT{8927b1a7-b49f-11ef-adb3-282e897391b3}.TMContainer00000000000000000002.regtrans-ms', 'ntuser.ini', 'OneDrive', 'PrintHood', 'Recent', 'Saved Games', 'Searches', 'SendTo', 'source', 'Start Menu', 'Templates', 'Videos']